### ISSUE TITLE
taiga_back error on clean install

### ISSUE THREAD

**Issue by grab-lab** [Monogramm/docker-taiga#24]
after clean install, an error was breaking the docker-compose up script
```
taiga_back      | Updating "admin" user with requested password...
taiga_back      | User "admin" updated with requested password
taiga_back      | [2019-07-29T12:55:08] Run contrib Slack plugin migrations to generate the new needed table
taiga_back      | Trying import local.py settings...
taiga_back      | Enabling Taiga emails...
taiga_back      | Taiga feedback enabled
taiga_back      | Taiga events enabled
taiga_back      | CommandError: App 'taiga_contrib_slack' does not have migrations.
taiga_back exited with code 1
```
i've try to disable the contrib plugins, but on next startup was following error
```
taiga_back      | [2019-07-29T13:06:03] Compiling messages and collecting static
taiga_back      | Trying import local.py settings...
taiga_back      | Enabling Taiga emails...
taiga_back      | Trying import local.py settings...
taiga_back      | Enabling Taiga emails...
taiga_back      | [2019-07-29T13:06:06] Start gunicorn server
taiga_back      |
taiga_back      | Error: '' is not a valid port number.
taiga_back      |
taiga_back exited with code 1
```

**Comment by madmath03** [comment]
The second error, `'' is not a valid port number.`, is already fixed, you just need to pull the latest image: `docker-compose pull`.
By the way, this is related to new parameters allowing to set the backend port and other gunicorn properties.

Regarding the first error, I think you must have an error in your docker-compose since I've just tested a fresh install a few minutes ago without any errors, and even the Travis-CI test suite does not get this error.

What version of the containers are you using ? Can you share your docker-compose.yml ?
Also, all those questions are part of the bug template, so please use the templates available next time you create an issue 😜

**Comment by grab-lab** [comment]
Thanks for your fast reply!
After pulling your new version, i've the same error ;(

```taiga_back      | [2019-07-30T07:32:25] Compiling messages and collecting static
taiga_back      | Trying import local.py settings...
taiga_back      | Enabling Taiga emails...
taiga_back      | Taiga feedback enabled
taiga_back      | Taiga events enabled
taiga_back      | Taiga contrib slack enabled
taiga_back      | Trying import local.py settings...
taiga_back      | Enabling Taiga emails...
taiga_back      | Taiga feedback enabled
taiga_back      | Taiga events enabled
taiga_back      | Taiga contrib slack enabled
taiga_back      | [2019-07-30T07:32:28] Start gunicorn server
taiga_back      |
taiga_back      | Error: '' is not a valid port number.
taiga_back      |
taiga_back exited with code 1
```
my docker-compose.yml and .env are completely stock - no manipulation

**Comment by madmath03** [comment]
If you really did **no** manipulation of the docker-compose, then that means you are building the docker images locally, so the previous command I gave you will have no effect since it only retrieves latest images, not rebuild local images.
You need to execute `docker-compose build --pull` to rebuild local images.

If you plan to modify the docker images locally, then that's fine, but if you only want to use our images as is, then I suggest you to follow the doc [Run Docker-compose](https://github.com/Monogramm/docker-taiga#run-docker-compose).

Also, even if you did no manipulation, what variant and version of the containers are you using ? Can you share your docker-compose.yml ?

**Comment by grab-lab** [comment]
thanks for help!

here my unmodified docker-compose.yml and my last log from docker-compose up. it seems your input helped, but the application stops working on taiga_back a little bit later (see behind)

thanks for your patience!!!

```
version: '2'

services:
  taigadb:
    image: postgres:10-alpine
    container_name: taigadb
    #restart: always
    ports:
      - 5432:5432
    volumes:
      - /srv/taiga/db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=taiga
      - POSTGRES_USER=taiga
      - POSTGRES_PASSWORD=${TAIGA_DB_PWD}

  taiga_back:
    build: ./back
    #image: monogramm/docker-taiga-back:4.2-alpine
    hostname: taiga.${DOMAIN}
    container_name: taiga_back
    #restart: always
    depends_on:
      - taigadb
    ports:
      - 8001:8001
    volumes:
      # Media and uploads directory. Required (or you will lose all uploads)
      - /srv/taiga/back/media:/usr/src/taiga-back/media
      - /srv/taiga/back/static:/usr/src/taiga-back/static
      # Taiga configuration directory. Makes it easier to change configuration with your own
      #- /srv/taiga/back/conf:/taiga
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      # Your hostname (REQUIRED)
      - TAIGA_HOSTNAME=taiga.${DOMAIN}
      #- TAIGA_SSL=False
      #- TAIGA_SSL_BY_REVERSE_PROXY=True
      # Secret key for cryptographic signing
      - TAIGA_SECRET_KEY=${TAIGA_SECRET}
      # Admin account default password
      - TAIGA_ADMIN_PASSWORD=${TAIGA_ADMIN_PASSWORD}
      # Database settings
      - TAIGA_DB_HOST=taigadb
      - TAIGA_DB_NAME=taiga
      - TAIGA_DB_USER=taiga
      - TAIGA_DB_PASSWORD=${TAIGA_DB_PWD}
      # when the db comes up from docker, it is usually too quick
      - TAIGA_SLEEP=5
      # To use an external SMTP for emails, fill in these values:
      - TAIGA_ENABLE_EMAIL=True
      - TAIGA_EMAIL_FROM=taiga@${TAIGA_EMAIL_DOMAIN}
      - TAIGA_EMAIL_USE_TLS=True
      - TAIGA_EMAIL_HOST=smtp.${TAIGA_EMAIL_DOMAIN}
      - TAIGA_EMAIL_PORT=587
      - TAIGA_EMAIL_USER=${TAIGA_SMTP_USER}
      - TAIGA_EMAIL_PASS=${TAIGA_SMTP_PWD}
      # Backend settings
      - TAIGA_DEBUG=False
      - TAIGA_PUBLIC_REGISTER_ENABLED=False
      - TAIGA_FEEDBACK_ENABLED=True
      - TAIGA_FEEDBACK_EMAIL=taiga@${TAIGA_EMAIL_DOMAIN}
      # Events settings
      - TAIGA_EVENTS_ENABLED=True
      - RABBIT_USER=${TAIGA_RABBIT_USER}
      - RABBIT_PASSWORD=${TAIGA_RABBIT_PASSWORD}
      - RABBIT_HOST=taiga_rabbit
      - RABBIT_PORT=5672
      # Async settings
      # To enable async mode, uncomment the following lines:
      #- TAIGA_ASYNC_ENABLED=True
      #- REDIS_HOST=taiga_redis
      #- REDIS_PORT=6379
      ### Additional parameters
      # Slack
      - TAIGA_ENABLE_SLACK=True
      # GitLab
      - TAIGA_ENABLE_GITLAB_AUTH=False
      - TAIGA_GITLAB_AUTH_URL=${TAIGA_GITLAB_AUTH_URL}
      - TAIGA_GITLAB_AUTH_CLIENT_ID=${TAIGA_GITLAB_AUTH_CLIENT_ID}
      - TAIGA_GITLAB_AUTH_CLIENT_SECRET=${TAIGA_GITLAB_AUTH_CLIENT_SECRET}
      # GitHub
      - TAIGA_ENABLE_GITHUB_AUTH=False
      - TAIGA_GITHUB_AUTH_CLIENT_ID=${TAIGA_GITHUB_AUTH_CLIENT_ID}
      - TAIGA_GITHUB_AUTH_CLIENT_SECRET=${TAIGA_GITHUB_AUTH_CLIENT_SECRET}
      # LDAP Settings
      - TAIGA_ENABLE_LDAP=False
      - TAIGA_LDAP_USE_TLS=True
      - TAIGA_LDAP_SERVER=ldap://${TAIGA_LDAP_DOMAIN}
      - TAIGA_LDAP_PORT=389
      - TAIGA_LDAP_BIND_DN=${TAIGA_LDAP_BIND_DN}
      - TAIGA_LDAP_BIND_PASSWORD=${TAIGA_LDAP_BIND_PASSWORD}
      - TAIGA_LDAP_BASE_DN=${TAIGA_LDAP_BASE_DN}
      - TAIGA_LDAP_USERNAME_ATTRIBUTE=uid
      - TAIGA_LDAP_EMAIL_ATTRIBUTE=mail
      - TAIGA_LDAP_FULL_NAME_ATTRIBUTE=cn
      - TAIGA_LDAP_FALLBACK=normal

  taiga_front:
    build: ./front
    #image: monogramm/docker-taiga-front:4.2-alpine
    hostname: taiga.${DOMAIN}
    container_name: taiga_front
    #restart: always
    depends_on:
      - taiga_back
      # To disable taiga-events, comment the following lines:
      - taiga_events
      - taiga_rabbit
      # To enable async mode, uncomment the following lines:
      #- taiga_redis
    ports:
      - 80:80
      - 443:443
    volumes:
      # Media and uploads directory. Required for NGinx
      - /srv/taiga/back/media:/usr/src/taiga-back/media:ro
      - /srv/taiga/back/static:/usr/src/taiga-back/static:ro
      # Taiga configuration directory. Makes it easier to change configuration with your own
      #- /srv/taiga/front/conf:/taiga
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      # Your hostname (REQUIRED)
      - TAIGA_HOSTNAME=taiga.${DOMAIN}
      #- TAIGA_SSL=True
      #- TAIGA_SSL_BY_REVERSE_PROXY=True
      # Frontend settings
      - TAIGA_DEBUG=false
      - TAIGA_DEBUG_INFO=false
      - TAIGA_DEFAULT_LANGUAGE=en
      - TAIGA_DEFAULT_THEME=taiga
      - TAIGA_PUBLIC_REGISTER_ENABLED=false
      - TAIGA_FEEDBACK_ENABLED=true
      - TAIGA_SUPPORT_URL=https://tree.taiga.io/support
      - TAIGA_PRIVACY_POLICY_URL=
      - TAIGA_TOS_URL=
      - TAIGA_GDPR_URL=
      - TAIGA_MAX_UPLOAD_SIZE=104857600
      - TAIGA_CONTRIB_PLUGINS=slack cookie-warning
      #- TAIGA_CONTRIB_PLUGINS=slack cookie-warning gitlab-auth github-auth
      - TAIGA_GRAVATAR=true
      - TAIGA_LOGIN_FORM_TYPE=ldap
      # Backend settings
      - TAIGA_BACK_HOST=taiga_back
      - TAIGA_BACK_PORT=8001
      # Events settings
      - TAIGA_EVENTS_ENABLED=True
      - TAIGA_EVENTS_HOST=taiga_events
      - TAIGA_EVENTS_PORT=8888
      ### Additional parameters
      # GitLab
      - TAIGA_GITLAB_AUTH_URL=${TAIGA_GITLAB_AUTH_URL}
      - TAIGA_GITLAB_AUTH_CLIENT_ID=${TAIGA_GITLAB_AUTH_CLIENT_ID}
      # GitHub
      - TAIGA_GITHUB_AUTH_CLIENT_ID=${TAIGA_GITHUB_AUTH_CLIENT_ID}

  # To disable taiga-events, comment all the following lines:
  taiga_rabbit:
    image: rabbitmq:3-alpine
    hostname: taiga_rabbit
    container_name: taiga_rabbit
    #restart: always
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=${TAIGA_RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${TAIGA_RABBIT_PASSWORD}

  taiga_events:
    image: monogramm/docker-taiga-events:alpine
    container_name: taiga_events
    #restart: always
    links:
      - taiga_rabbit
    ports:
      - 8888:8888
    environment:
      - RABBIT_USER=${TAIGA_RABBIT_USER}
      - RABBIT_PASSWORD=${TAIGA_RABBIT_PASSWORD}
      - RABBIT_HOST=taiga_rabbit
      - RABBIT_PORT=5672
      - TAIGA_EVENTS_SECRET=${TAIGA_SECRET}
      - TAIGA_EVENTS_PORT=8888

  # To enable async mode, uncomment the following lines:
#  taiga_redis:
#    image: redis:4.0-alpine
#    container_name: taiga_redis
#    restart: always
#    ports:
#      - 6379:6379
#    volumes:
#      - /srv/taiga/redis/:/data
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#
#  # FIXME Celery docker image is deprecated since 2017
#  taiga_celery:
#    image: celery
#    container_name: taiga_celery
#    restart: always
#    links:
#      - taiga_rabbit
#      - taiga_redis
```
```
Starting taigadb      ... done
Starting taiga_rabbit ... done
Starting taiga_back   ... done
Starting taiga_events ... done
Starting taiga_front  ... done
Attaching to taigadb, taiga_rabbit, taiga_events, taiga_back, taiga_front
taigadb         | 2019-07-31 10:05:08.126 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
taiga_events    | Updating Taiga RabbitMQ URL: taiga_rabbit
taigadb         | 2019-07-31 10:05:08.126 UTC [1] LOG:  listening on IPv6 address "::", port 5432
taiga_events    | Updating Taiga Events secret: (don't expect to find those in the logs...)
taigadb         | 2019-07-31 10:05:08.131 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
taiga_events    | Updating Taiga Events default port: 8888
taigadb         | 2019-07-31 10:05:08.148 UTC [18] LOG:  database system was shut down at 2019-07-31 10:04:53 UTC
taigadb         | 2019-07-31 10:05:08.209 UTC [1] LOG:  database system is ready to accept connections
taiga_front     | [2019-07-31T12:05:09] Enabling Taiga Events
taiga_front     | [2019-07-31T12:05:09] Updating Taiga Front debug status: false
taiga_front     | [2019-07-31T12:05:09] Updating Taiga Front debug info status: false
taiga_front     | [2019-07-31T12:05:09] Updating Taiga Front default language: en
taiga_front     | [2019-07-31T12:05:09] Updating Taiga Front default theme: taiga
taiga_front     | [2019-07-31T12:05:09] Updating Taiga Front public registration status: false
taiga_front     | [2019-07-31T12:05:09] Updating Taiga Front feedback status: true
taiga_front     | [2019-07-31T12:05:09] Updating Taiga Front support URL: https://tree.taiga.io/support
taiga_front     | [2019-07-31T12:05:09] Reset Taiga Front privacy policy URL
taiga_front     | [2019-07-31T12:05:09] Reset Taiga Front terms of services URL
taiga_front     | [2019-07-31T12:05:09] Reset Taiga Front GDPR compliance URL
taiga_front     | [2019-07-31T12:05:09] Updating Taiga Front max upload file size: 104857600
taiga_front     | [2019-07-31T12:05:09] Updating Taiga Front contribution plugins list: slack cookie-warning
taiga_front     | [2019-07-31T12:05:09] Reset Taiga Front importers list
taiga_front     | [2019-07-31T12:05:09] Updating Taiga Front Gravatar status: true
taiga_front     | [2019-07-31T12:05:09] Updating Taiga Front login form type: ldap
taiga_front     | [2019-07-31T12:05:09] Updating Taiga Back connection: taiga_back
taiga_front     | [2019-07-31T12:05:09] Updating Taiga Events connection: taiga_events
taiga_front     | [2019-07-31T12:05:09] Checking nginx configuration...
taiga_front     | nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
taiga_front     | nginx: configuration file /etc/nginx/nginx.conf test is successful
taiga_front     | [2019-07-31T12:05:09] Start nginx server...
taiga_back      | [2019-07-31T12:05:13] Running database check
taiga_back      | Connecting to database:
taiga_back      | dbname='taiga' user='taiga' host='taigadb' password='******'
taiga_back      | [2019-07-31T12:05:13] Execute database migrations...
taiga_rabbit    | 2019-07-31 10:05:13.916 [info] <0.8.0> Feature flags: list of feature flags found:
taiga_rabbit    | 2019-07-31 10:05:13.917 [info] <0.8.0> Feature flags: feature flag states written to disk: yes
taiga_rabbit    | 2019-07-31 10:05:13.980 [info] <0.263.0>
taiga_rabbit    |  Starting RabbitMQ 3.7.17 on Erlang 22.0.7
taiga_rabbit    |  Copyright (C) 2007-2019 Pivotal Software, Inc.
taiga_rabbit    |  Licensed under the MPL.  See https://www.rabbitmq.com/
taiga_rabbit    |
taiga_rabbit    |   ##  ##
taiga_rabbit    |   ##  ##      RabbitMQ 3.7.17. Copyright (C) 2007-2019 Pivotal Software, Inc.
taiga_rabbit    |   ##########  Licensed under the MPL.  See https://www.rabbitmq.com/
taiga_rabbit    |   ######  ##
taiga_rabbit    |   ##########  Logs: <stdout>
taiga_rabbit    |
taiga_rabbit    |               Starting broker...
taiga_rabbit    | 2019-07-31 10:05:13.980 [info] <0.263.0>
taiga_rabbit    |  node           : rabbit@taiga_rabbit
taiga_rabbit    |  home dir       : /var/lib/rabbitmq
taiga_rabbit    |  config file(s) : /etc/rabbitmq/rabbitmq.conf
taiga_rabbit    |  cookie hash    : QZ4PmUmXfoKJ8ZZiJbGJmA==
taiga_rabbit    |  log(s)         : <stdout>
taiga_rabbit    |  database dir   : /var/lib/rabbitmq/mnesia/rabbit@taiga_rabbit
taiga_rabbit    | 2019-07-31 10:05:13.987 [info] <0.263.0> Running boot step pre_boot defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:13.987 [info] <0.263.0> Running boot step rabbit_core_metrics defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:13.988 [info] <0.263.0> Running boot step rabbit_alarm defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:13.991 [info] <0.287.0> Memory high watermark set to 3147 MiB (3300532224 bytes) of 7869 MiB (8251330560 bytes) total
taiga_rabbit    | 2019-07-31 10:05:13.995 [info] <0.289.0> Enabling free disk space monitoring
taiga_rabbit    | 2019-07-31 10:05:13.995 [info] <0.289.0> Disk free limit set to 50MB
taiga_rabbit    | 2019-07-31 10:05:13.997 [info] <0.263.0> Running boot step code_server_cache defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:13.997 [info] <0.263.0> Running boot step file_handle_cache defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:13.997 [info] <0.293.0> FHC read buffering:  OFF
taiga_rabbit    | 2019-07-31 10:05:13.997 [info] <0.293.0> FHC write buffering: ON
taiga_rabbit    | 2019-07-31 10:05:13.997 [info] <0.292.0> Limiting to approx 1048476 file handles (943626 sockets)
taiga_rabbit    | 2019-07-31 10:05:13.998 [info] <0.263.0> Running boot step worker_pool defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:13.998 [info] <0.266.0> Will use 4 processes for default worker pool
taiga_rabbit    | 2019-07-31 10:05:13.998 [info] <0.266.0> Starting worker pool 'worker_pool' with 4 processes in it
taiga_rabbit    | 2019-07-31 10:05:13.998 [info] <0.263.0> Running boot step database defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:13.999 [info] <0.263.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
taiga_rabbit    | 2019-07-31 10:05:14.016 [info] <0.263.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
taiga_rabbit    | 2019-07-31 10:05:14.016 [info] <0.263.0> Peer discovery backend rabbit_peer_discovery_classic_config does not support registration, skipping registration.
taiga_rabbit    | 2019-07-31 10:05:14.016 [info] <0.263.0> Running boot step database_sync defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.016 [info] <0.263.0> Running boot step feature_flags defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.016 [info] <0.263.0> Running boot step codec_correctness_check defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.016 [info] <0.263.0> Running boot step external_infrastructure defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.016 [info] <0.263.0> Running boot step rabbit_registry defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.017 [info] <0.263.0> Running boot step rabbit_auth_mechanism_cr_demo defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.017 [info] <0.263.0> Running boot step rabbit_queue_location_random defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.017 [info] <0.263.0> Running boot step rabbit_event defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.017 [info] <0.263.0> Running boot step rabbit_auth_mechanism_amqplain defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.017 [info] <0.263.0> Running boot step rabbit_auth_mechanism_plain defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.017 [info] <0.263.0> Running boot step rabbit_exchange_type_direct defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.017 [info] <0.263.0> Running boot step rabbit_exchange_type_fanout defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.017 [info] <0.263.0> Running boot step rabbit_exchange_type_headers defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.017 [info] <0.263.0> Running boot step rabbit_exchange_type_topic defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.017 [info] <0.263.0> Running boot step rabbit_mirror_queue_mode_all defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.017 [info] <0.263.0> Running boot step rabbit_mirror_queue_mode_exactly defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.017 [info] <0.263.0> Running boot step rabbit_mirror_queue_mode_nodes defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.018 [info] <0.263.0> Running boot step rabbit_priority_queue defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.018 [info] <0.263.0> Priority queues enabled, real BQ is rabbit_variable_queue
taiga_rabbit    | 2019-07-31 10:05:14.018 [info] <0.263.0> Running boot step rabbit_queue_location_client_local defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.018 [info] <0.263.0> Running boot step rabbit_queue_location_min_masters defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.018 [info] <0.263.0> Running boot step kernel_ready defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.018 [info] <0.263.0> Running boot step rabbit_sysmon_minder defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.018 [info] <0.263.0> Running boot step rabbit_epmd_monitor defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.020 [info] <0.263.0> Running boot step guid_generator defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.023 [info] <0.263.0> Running boot step rabbit_node_monitor defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.023 [info] <0.320.0> Starting rabbit_node_monitor
taiga_rabbit    | 2019-07-31 10:05:14.024 [info] <0.263.0> Running boot step delegate_sup defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.024 [info] <0.263.0> Running boot step rabbit_memory_monitor defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.024 [info] <0.263.0> Running boot step core_initialized defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.024 [info] <0.263.0> Running boot step upgrade_queues defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.036 [info] <0.263.0> Running boot step rabbit_connection_tracking defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.036 [info] <0.263.0> Running boot step rabbit_connection_tracking_handler defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.036 [info] <0.263.0> Running boot step rabbit_exchange_parameters defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.036 [info] <0.263.0> Running boot step rabbit_mirror_queue_misc defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.036 [info] <0.263.0> Running boot step rabbit_policies defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.037 [info] <0.263.0> Running boot step rabbit_policy defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.037 [info] <0.263.0> Running boot step rabbit_queue_location_validator defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.037 [info] <0.263.0> Running boot step rabbit_vhost_limit defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.037 [info] <0.263.0> Running boot step recovery defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.039 [info] <0.349.0> Making sure data directory '/var/lib/rabbitmq/mnesia/rabbit@taiga_rabbit/msg_stores/vhosts/628WB79CIFDYO9LJI6DKMI09L' for vhost '/' exists
taiga_rabbit    | 2019-07-31 10:05:14.041 [info] <0.349.0> Starting message stores for vhost '/'
taiga_rabbit    | 2019-07-31 10:05:14.041 [info] <0.353.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_transient": using rabbit_msg_store_ets_index to provide index
taiga_rabbit    | 2019-07-31 10:05:14.043 [info] <0.349.0> Started message store of type transient for vhost '/'
taiga_rabbit    | 2019-07-31 10:05:14.043 [info] <0.356.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent": using rabbit_msg_store_ets_index to provide index
taiga_rabbit    | 2019-07-31 10:05:14.044 [info] <0.349.0> Started message store of type persistent for vhost '/'
taiga_rabbit    | 2019-07-31 10:05:14.045 [info] <0.263.0> Running boot step empty_db_check defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.045 [info] <0.263.0> Running boot step rabbit_looking_glass defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.045 [info] <0.263.0> Running boot step rabbit_core_metrics_gc defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.045 [info] <0.263.0> Running boot step background_gc defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.046 [info] <0.263.0> Running boot step connection_tracking defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.046 [info] <0.263.0> Setting up a table for connection tracking on this node: tracked_connection_on_node_rabbit@taiga_rabbit
taiga_rabbit    | 2019-07-31 10:05:14.046 [info] <0.263.0> Setting up a table for per-vhost connection counting on this node: tracked_connection_per_vhost_on_node_rabbit@taiga_rabbit
taiga_rabbit    | 2019-07-31 10:05:14.046 [info] <0.263.0> Running boot step routing_ready defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.046 [info] <0.263.0> Running boot step pre_flight defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.046 [info] <0.263.0> Running boot step notify_cluster defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.046 [info] <0.263.0> Running boot step networking defined by app rabbit
taiga_rabbit    | 2019-07-31 10:05:14.047 [warning] <0.379.0> Setting Ranch options together with socket options is deprecated. Please use the new map syntax that allows specifying socket options separately from other options.
taiga_rabbit    | 2019-07-31 10:05:14.048 [info] <0.393.0> started TCP listener on [::]:5672
taiga_rabbit    | 2019-07-31 10:05:14.048 [info] <0.263.0> Running boot step direct_client defined by app rabbit
taiga_rabbit    |  completed with 0 plugins.
taiga_rabbit    | 2019-07-31 10:05:14.101 [info] <0.8.0> Server startup complete; 0 plugins started.
taiga_back      | Trying import local.py settings...
taiga_back      | Enabling Taiga emails...
taiga_back      | Taiga feedback enabled
taiga_back      | Taiga events enabled
taiga_back      | Taiga contrib slack enabled
taiga_back      | Operations to perform:
taiga_back      |   Apply all migrations: admin, attachments, auth, bitbucket, contact, contenttypes, custom_attributes, djmail, easy_thumbnails, epics, external_apps, feedback, github, gitlab, gogs, history, issues, likes, milestones, notifications, projects, references, sessions, settings, taiga_contrib_slack, tasks, timeline, users, userstorage, userstories, votes, webhooks, wiki
taiga_back      | Running migrations:
taiga_back      |   No migrations to apply.
taiga_back      | [2019-07-31T12:05:15] Compiling messages and collecting static
taiga_back      | Trying import local.py settings...
taiga_back      | Enabling Taiga emails...
taiga_back      | Taiga feedback enabled
taiga_back      | Taiga events enabled
taiga_back      | Taiga contrib slack enabled
taiga_back      | Trying import local.py settings...
taiga_back      | Enabling Taiga emails...
taiga_back      | Taiga feedback enabled
taiga_back      | Taiga events enabled
taiga_back      | Taiga contrib slack enabled
taiga_back      | [2019-07-31T12:05:18] Start gunicorn server
taiga_back      | [2019-07-31 12:05:18 +0200] [1] [INFO] Starting gunicorn 19.7.1
taiga_back      | [2019-07-31 12:05:18 +0200] [1] [INFO] Listening at: http://0.0.0.0:8001 (1)
taiga_back      | [2019-07-31 12:05:18 +0200] [1] [INFO] Using worker: sync
taiga_back      | [2019-07-31 12:05:18 +0200] [194] [INFO] Booting worker with pid: 194
taiga_back      | [2019-07-31 12:05:18 +0200] [205] [INFO] Booting worker with pid: 205
taiga_back      | [2019-07-31 12:05:18 +0200] [216] [INFO] Booting worker with pid: 216
taiga_back      | [2019-07-31 12:05:18 +0200] [227] [INFO] Booting worker with pid: 227
taiga_back      | Trying import local.py settings...
taiga_back      | Enabling Taiga emails...
taiga_back      | Taiga feedback enabled
taiga_back      | Taiga events enabled
taiga_back      | Taiga contrib slack enabled
taiga_back      | Trying import local.py settings...
taiga_back      | Enabling Taiga emails...
taiga_back      | Taiga feedback enabled
taiga_back      | Taiga events enabled
taiga_back      | Taiga contrib slack enabled
taiga_back      | Trying import local.py settings...
taiga_back      | Enabling Taiga emails...
taiga_back      | Taiga feedback enabled
taiga_back      | Taiga events enabled
taiga_back      | Taiga contrib slack enabled
taiga_back      | Trying import local.py settings...
taiga_back      | Enabling Taiga emails...
taiga_back      | Taiga feedback enabled
taiga_back      | Taiga events enabled
taiga_back      | Taiga contrib slack enabled
```
